# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.4-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/ez

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-easy-{{ .Branch }}-{{ checksum "package-lock.json" }}

          # fallback to using the latest cache if no exact match is found
          - v1-easy-
      
      - run: npm i

      - persist_to_workspace:
          root: .
          paths:
            - ./*

      - save_cache:
          paths:
            - node_modules
          key: v1-easy-{{ .Branch }}-{{ checksum "package-lock.json" }}

  lint:
    docker:
      - image: circleci/node:8.11.4-browsers
    working_directory: ~/ez
    steps:
      - attach_workspace:
          at: .

      # run lint
      - run: npm run lint

  build:
    docker:
      - image: circleci/node:8.11.4-browsers
    working_directory: ~/ez
    steps:
      - attach_workspace:
          at: .

      # run build
      - run: npm run build

  test:
    docker:
      - image: circleci/node:8.11.4-browsers
    working_directory: ~/ez
    steps:
      - attach_workspace:
          at: .
          
      # run unit tests
      - run: npm run test

  e2e:
    docker:
      - image: circleci/node:8.11.4-browsers
    working_directory: ~/ez
    steps:
      - attach_workspace:
          at: .
          
      # run e2e tests
      - run: npm run e2e

workflows:
  version: 2
  default_workflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
