# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Workflow variables
base_image: &base_image

  # Specify the node version here
  image: circleci/node:10.15.0-browsers

job_common: &job_common
  docker:
    - <<: *base_image
  working_directory: ~/easy

# Save dependencies to cache
save: &save
  save_cache:
    key: v1-easy-{{ .Branch }}-{{ checksum "package-lock.json" }}
    paths:
      - node_modules

# Restore cached dependencies
restore: &restore
  restore_cache:
    keys:
      - v1-easy-{{ .Branch }}-{{ checksum "package-lock.json" }}

      # Fallback in case checksum fails
      - v1-easy-{{ .Branch }}-

# Workflow jobs
jobs:
  install:
    <<: *job_common

    steps:

      # Checkout git repo
      - checkout

      # Restore cached dependencies
      - <<: *restore

      - run:
          name: Update npm
          command: sudo npm i -g npm --silent

      - run:
          name: Update dependencies
          command: npm i --silent
      
      # Cache dependencies
      - <<: *save          

  build:
    <<: *job_common

    steps:
      - checkout

      - <<: *restore

      - run:
          name: Build easy and docs
          command: npm run build

      # Add dependencies to workspace
      - persist_to_workspace:
          root: .
          paths:
            - .

  test_easy:
    <<: *job_common

    steps:
      - attach_workspace:
          at: .
          
      - run:
          name: Run easy unit tests
          command: npm run test:easy

      - run:
          name: Upload easy code coverage report to codecov 
          command: bash <(curl -s https://codecov.io/bash) -c -F easy

  test_docs:
    <<: *job_common

    steps:
      - attach_workspace:
          at: .
          
      - run:
          name: Run docs unit tests
          command: npm run test:docs
      
      - run:
          name: Upload docs code coverage report to codecov 
          command: bash <(curl -s https://codecov.io/bash) -c -F docs

  e2e:
    <<: *job_common

    steps:
      - attach_workspace:
          at: .
          
      - run:
          name: Install correct selenium webdriver
          command: npm run update:webdriver

      - run:
          name: Run docs e2e tests
          command: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js --webdriver-update=false

workflows:
  default_workflow:
    jobs:
      - install
      - build:
          requires:
            - install
      - test_easy:
          requires:
            - build
      - test_docs:
          requires:
            - build
      - e2e:
          requires:
            - build
